;SOUMYA PRAKASH BISWAL
;2141002122
;FIND THE LARGEST NO IN AN ARRAY 

.DATA
SIZE DB 04H
VALUE DB 0FH,09H,14H,10H
RES DB 0

.CODE
MAIN PROC 
     MOV AX,DATA ;DATA =0710
     MOV DS,AX
     MOV CL,SIZE
     DEC CL
     LEA SI,VALUE
     MOV AL,[SI]
UP: INC SI
    CMP AL,[SI]
    JNC DN
    MOV AL,[SI] 
    
DN: DEC CL
    JNZ UP
    LEA DI,RES
    MOV [DI],AL 

END MAIN